### ISSUE TITLE
Alias in .bashrc not working in Procfiles

### ISSUE THREAD

**Issue by giacomocerquone** [heroku/heroku-local#41]
Hi, I opened this issue also on node-foreman.
First of all thanks for you work! I've spent so much time trying to solve this problem that I don't know anymore where to ask.
The problem is simple:

I have this alias in my .bashrc file:
alias python=python3
and I'm using node-foremon in the heroku cli environment with this procfile:
worker: python botcore.py.

When I try to launch that 'worker' it goes to take python2.7 (the default python) so the alias is not working (if I give python in the shell I obviously get python 3). This is due probably to the fact that aliases don't work in non interactive shells.

How can I solve this dilemma?

**Comment by jdx** [comment]
aliases won't be used by heroku local because it's not using bash, it's just executing whatever is on your PATH and aliases are not on the PATH. Here is what I would do:

First, add ./bin to your path with `export PATH=./bin:$PATH` in your bashrc
Next, symlink python to python3 in the root of the project: `ln -s $(which python3) ./bin/python`

Now if you run `heroku local:run python --version` you should see v3

**Comment by jdx** [comment]
closing since this is not an issue with heroku local

**Comment by giacomocerquone** [comment]
@jdxcode thank you very much for the support, the point is that linking from python3 to python is considered always a bad idea since it could cause lots of troubles to the os. Is this the only way?

**Comment by jdx** [comment]
my solution keeps it local to your project only so it won't mess with anything in the system
